def set_operations():
    setA_math = set(input("enter the students name enrolled in maths: ").split())
    setB_scie = set(input(" enter the students name enrolled in science:").split())
    print("students in math: ",setA_math)
    print("students in science: ",setB_scie)
    setAB = setA_math.intersection(setB_scie)
    print("students enrolled in math and science: ",setAB)
    setA_B = setA_math.difference(setB_scie)
    print("students enrolled in maths but not in science: ",setA_B)
    setUAB = setA_math.union(setB_scie)
    print("students enrolled in either math or science or both : ",setUAB)
    setB_A = setB_scie.difference(setA_math)
    print("students in science but not in maths :   ",setB_A)
set_operations()